const CONSTANTS = {
    CARDS: [
        {
            IMAGE_URL: '/images/product1.jpg',
            NAME: 'Jeleuri',
            PRICE: 10 ,
            PRICE_UNIT:'lei/100g',
            ID:1,
            AMOUNT: 1,
        },
        {
            IMAGE_URL: '/images/product2.jpg',
            NAME: 'Ciocolata',
            PRICE: 2 ,
            PRICE_UNIT:'lei/buc',
            ID: 2,
            AMOUNT: 1,
        },
        {
            IMAGE_URL: '/images/product3.jpg',
            NAME: 'Clatite',
            PRICE: 12 ,
            PRICE_UNIT:'lei/250g',
            ID: 3,
            AMOUNT: 1,
        },
        {
            IMAGE_URL: '/images/product4.jpg',
            NAME: 'Prajituri',
            PRICE: 12,
            PRICE_UNIT:'lei/100g',
            ID: 4,
            AMOUNT: 1,
        },
        {
            IMAGE_URL: '/images/product5.jpg',
            NAME: 'Bomboane',
            PRICE: 8 ,
            PRICE_UNIT:'lei/100g',
            ID: 5,
            AMOUNT: 1,
        },
        {
            IMAGE_URL: '/images/product6.jpg',
            NAME: 'Biscuiti',
            PRICE: 10 ,
            PRICE_UNIT:'lei/100g',
            ID: 6,
            AMOUNT: 1,
        },
        {
            IMAGE_URL: '/images/product7.jpg',
            NAME: 'Prajitura',
            PRICE: 10 ,
            PRICE_UNIT:'lei/100g',
            ID: 7,
            AMOUNT: 1,
        },
        {
            IMAGE_URL: '/images/product8.jpg',
            NAME: 'Prajitura',
            PRICE: 12 ,
            PRICE_UNIT:'lei/100g',
            ID: 8,
            AMOUNT: 1,
        },
        {
            IMAGE_URL: '/images/product9.jpg',
            NAME: 'Morcovel',
            PRICE: 12 ,
            PRICE_UNIT:'lei/100g',
            ID: 9,
            AMOUNT: 1,
        },
    ],
};
export default CONSTANTS;
